### ISSUE TITLE
Gleiches AddOn

### ISSUE THREAD

**Issue by olien** [myCodebox/url_checker#2]
Hi,

wir hatten solch einen URL Checker auch mal angefangen (und noch nicht wirklich fertig).

Vielleicht magst Du dir das mal angucken: https://github.com/FriendsOfREDAXO/linkchecker
Würde mich freuen wenn es ein (fertiges) AddOn gibt welches die URLs checkt :-)

Könnte Dein Projekt ein FoR Projekt werden (zwei gleichartige AddOns benötigen wir ja nicht?

Wenn Du magst komm doch zu uns in den Slack Channel: http://redaxo.org/slack/
Würde uns freuen!

LG
Oliver

( Guck mal @dtpop )

**Comment by myCodebox** [comment]
Danke für den Tipp

**Comment by myCodebox** [comment]
Du hast mich ja schon Mal angeschrieben, da war ich gerade mit einer Firmen Gründung beschäftigt, dadurch ist das Ganze dann unter gegangen.

Ich schau mir mal das Addon an.


Danke,
Herbert
Am 05.03.2019 11:22:15 schrieb Oliver Kreischer <notifications@github.com>:
Hi,
wir hatten solch einen URL Checker auch mal angefangen (und noch nicht wirklich fertig).
Vielleicht magst Du dir das mal angucken: https://github.com/FriendsOfREDAXO/linkchecker [https://github.com/FriendsOfREDAXO/linkchecker]
Würde mich freuen wenn es ein (fertiges) AddOn gibt welches die URLs checkt :-)
Könnte Dein Projekt ein FoR Projekt werden (zwei gleichartige AddOns benötigen wir ja nicht?
LG
Oliver
( Guck mal @dtpop [https://github.com/dtpop] )
